Kaggle Report
========================================================
Introduction
------------------
How well does the EHR population represent the general population of the United States? In which specific areas doe we expect EHR to misrepresent the general population?

Methods
-------------------
### Data Sources
#### 1. EHR 
Practice Fusion provided Kaggle with a dateset of de-identified electronic health records.
#### 2. Census 
I downloaded census data from data.gov for the 2010 census. For population data, I used the estimates for 2011. 

### Data Prep
#### 1. Age
The EHR data provided year of birth for the patients. I transformed this to age by subtracting year of birth from 2012. The census data also includes age. For interpretation, I binned age data into three age groups: young (18-34), middle (35-64), old (65+). EHR does not include any patients under 18. 
#### 2. Gender
Both EHR and the census include gender. The rate of smoking differs significantly with gender, so I grouped the analysis. 
#### 3. Smoking Status
The EHR data used NIST codes to identify smoking status of patients. I binned the NIST codes into a single binary smoker/non-smoker variate. 
#### 4. Space (state and division)
There was not good enough spatial coverage in the EHR dataset to generate good summary statistics for all states. So, I aggregated the states into division. The upside to this is that it is much easier to understand nine division than 50+ states. The downside is that smoking rates do tend to vary due to state level anti-smoking policies. I included D.C. in the South Atlantic division and removed the thirty patients from Puerto Rico. 
#### BMI/weight

Issues
------------------
1. Some data for minors was included in data set. If you subtract YearOfBirth from VisitYear (excluding records where VisitYear=0) you find 819 records for minors. The youngest individual being 15 years old. This is presumably why there are records from Pediatricians in the dataset. I assume this was unintentional. 

2. We have several records for individuals less than three feet tall or greater than nine feet tall. Also folks who weight less than fifty pounds or greater than 600 pounds. 